#!/bin/php
<?php include('bspwm.class.php');

$wallpaper = '~/bg4.jpg';

$autostart = [
'sxhkd',
'numlockx',
'xsetroot -cursor_name left_ptr',
'compton -f --vsync drm',
'tint2',
"feh --bg-scale $wallpaper" 
];


//РАМКИ И ГАПСЫ
$border_width = '1';
$window_gap = '10';

$normal_border_color = '"#23252e"';
$active_border_color = '"#23252e"';
$focused_border_color = '"#f9f8fe"';

//ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
$presel_feedback_color = '"fd2e59"';




/*  ПРИ ПОМОЩИ ЭТОЙ ХРЕНИ МОЖНО СДЕЛАТЬ ГАПСЫ ТОЛЬКО МЕЖДУ ОКНАМИ

    bspc config window_gap $gap;
    bspc config top_padding -$(($gap+2))
    bspc config left_padding -$(($gap+2))
    bspc config right_padding -$(($gap+4))
    bspc config bottom_padding $(($PANEL_HEIGHT-$gap))      */



//КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
$split_ratio = '0.5';
//ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
$focus_follows_pointer = 'true';
$pointer_modifier = 'super';

//РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
$single_monocle = 'false';

//ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
$borderless_monocle = 'false';
$gapless_monocle = 'false';
$paddingless_monocle = 'true';

//СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
//$automatic_scheme = 'spiral';


//ПРАВИЛА ОКОН
$dmenu_rule = '-a dmenu rectangle=900x22+610+90';




























$bspwm->autostart($autostart);
$bspwm->config('border_width', $border_width);
$bspwm->config('window_gap', $window_gap);
$bspwm->config('normal_border_color', $normal_border_color);
$bspwm->config('active_border_color', $active_border_color);
$bspwm->config('focused_border_color', $focused_border_color);
$bspwm->config('presel_feedback_color', $presel_feedback_color);
$bspwm->config('split_ratio', $split_ratio);
$bspwm->config('focus_follows_pointer', $focus_follows_pointer);
$bspwm->config('pointer_modifier', $pointer_modifier);
$bspwm->config('single_monocle', $single_monocle);
$bspwm->config('borderless_monocle', $borderless_monocle);
$bspwm->config('gapless_monocle', $gapless_monocle);
$bspwm->config('paddingless_monocle', $paddingless_monocle);
$bspwm->rule($dmenu_rule);
$bspwm->wallpaper($wallpaper);

